name: seurat5
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - _r-mutex=1.0.1=anacondar_1
  - _r-xgboost-mutex=2.0=cpu_0
  - argcomplete=1.12.3=pyhd8ed1ab_0
  - aws-c-auth=0.7.15=h70caa3e_0
  - aws-c-cal=0.6.9=h14ec70c_3
  - aws-c-common=0.9.12=hd590300_0
  - aws-c-compression=0.2.17=h572eabf_8
  - aws-c-event-stream=0.4.1=h17cd1f3_5
  - aws-c-http=0.8.0=hc6da83f_5
  - aws-c-io=0.14.3=h3c8c088_1
  - aws-c-mqtt=0.10.1=h0ef3971_3
  - aws-c-s3=0.5.0=h1b46bed_2
  - aws-c-sdkutils=0.1.14=h572eabf_0
  - aws-checksums=0.1.17=h572eabf_7
  - aws-crt-cpp=0.26.1=h33f84b2_9
  - aws-sdk-cpp=1.11.242=h65f022c_0
  - binutils_impl_linux-64=2.40=hf600244_0
  - bioconductor-annotate=1.78.0=r43hdfd78af_0
  - bioconductor-annotationdbi=1.62.2=r43hdfd78af_0
  - bioconductor-aucell=1.22.0=r43hdfd78af_0
  - bioconductor-basilisk=1.12.1=r43hdfd78af_0
  - bioconductor-basilisk.utils=1.12.1=r43hdfd78af_0
  - bioconductor-beachmat=2.16.0=r43hf17093f_0
  - bioconductor-biobase=2.60.0=r43ha9d7317_0
  - bioconductor-biocgenerics=0.46.0=r43hdfd78af_0
  - bioconductor-biocneighbors=1.18.0=r43hf17093f_0
  - bioconductor-biocparallel=1.34.2=r43hf17093f_0
  - bioconductor-biocsingular=1.16.0=r43hf17093f_0
  - bioconductor-biomart=2.56.1=r43hdfd78af_0
  - bioconductor-biostrings=2.68.1=r43ha9d7317_0
  - bioconductor-bluster=1.10.0=r43hf17093f_0
  - bioconductor-complexheatmap=2.16.0=r43hdfd78af_0
  - bioconductor-data-packages=20231203=hdfd78af_0
  - bioconductor-delayedarray=0.26.6=r43ha9d7317_0
  - bioconductor-delayedmatrixstats=1.22.1=r43hdfd78af_0
  - bioconductor-densvis=1.10.2=r43hf17093f_0
  - bioconductor-dir.expiry=1.8.0=r43hdfd78af_0
  - bioconductor-edger=3.42.4=r43hf17093f_0
  - bioconductor-fgsea=1.26.0=r43hf17093f_0
  - bioconductor-genomeinfodb=1.36.1=r43hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.11=r43hdfd78af_1
  - bioconductor-genomicranges=1.52.0=r43ha9d7317_0
  - r-ggalluvial=0.12.5
  - bioconductor-graph=1.78.0=r43ha9d7317_0
  - bioconductor-gseabase=1.62.0=r43hdfd78af_0
  - bioconductor-iranges=2.34.1=r43ha9d7317_0
  - bioconductor-keggrest=1.40.0=r43hdfd78af_0
  - bioconductor-limma=3.56.2=r43ha9d7317_0
  - bioconductor-matrixgenerics=1.12.2=r43hdfd78af_0
  - bioconductor-metapod=1.8.0=r43hf17093f_0
  - bioconductor-rcistarget=1.20.0=r43hdfd78af_0
  - bioconductor-s4arrays=1.0.4=r43ha9d7317_0
  - bioconductor-s4vectors=0.38.1=r43ha9d7317_0
  - bioconductor-scaledmatrix=1.8.1=r43hdfd78af_0
  - bioconductor-scater=1.28.0=r43hdfd78af_0
  - bioconductor-scran=1.28.1=r43hf17093f_0
  - bioconductor-scuttle=1.10.1=r43hf17093f_0
  - bioconductor-singlecellexperiment=1.22.0=r43hdfd78af_0
  - bioconductor-sparsearray=1.0.10=r43ha9d7317_0
  - bioconductor-sparsematrixstats=1.12.2=r43hf17093f_0
  - bioconductor-speckle=1.0.0=r43hdfd78af_0
  - bioconductor-summarizedexperiment=1.30.2=r43hdfd78af_0
  - bioconductor-xvector=0.40.0=r43ha9d7317_0
  - bioconductor-zlibbioc=1.46.0=r43ha9d7317_0
  - blas=1.0=openblas
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.26.0=hd590300_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - curl=8.5.0=hca28451_0
  - dart-sass=1.58.3=ha770c72_1
  - deno=1.37.2=h335b0a9_1
  - deno-dom=0.1.35=hd9586b0_1
  - esbuild=0.19.2=ha770c72_0
  - expat=2.5.0=hcb278e6_1
  - fftw=3.3.9=h5eee18b_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=13.2.0=h338b0a0_5
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - gfortran_impl_linux-64=13.2.0=h76e1118_5
  - glib=2.78.3=hfc55251_0
  - glib-tools=2.78.3=hfc55251_0
  - glog=0.6.0=h6f12383_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h59595ed_0
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=13.2.0=h338b0a0_5
  - harfbuzz=8.3.0=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - joblib=1.1.1=py37h06a4308_0
  - jq=1.7.1=hd590300_0
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarrow=13.0.0=hf0f33ac_25_cpu
  - libblas=3.9.0=21_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.5.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=13.2.0=ha9c7c90_105
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgit2=1.7.2=h76de150_0
  - libglib=2.78.3=h783c2da_0
  - libgomp=13.2.0=h807b86a_5
  - libgoogle-cloud=2.12.0=hef10d8f_5
  - libgrpc=1.60.1=h74775cd_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=21_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.16=h0b41bf4_1
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.42=h2797004_0
  - libprotobuf=4.25.1=hf27288f_1
  - libre2-11=2023.06.02=h7a70373_0
  - libsanitizer=13.2.0=h7e041cc_5
  - libsqlite=3.45.1=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=13.2.0=ha9c7c90_105
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=ha9c0a0a_2
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxgboost=2.0.3=h6a678d5_0
  - libxml2=2.12.5=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - make=4.3=hd18ef5c_1
  - ncurses=6.4=h59595ed_2
  - numpy=1.21.5=py37hf838250_3
  - numpy-base=1.21.5=py37h1e6e340_3
  - oniguruma=6.9.9=hd590300_0
  - openssl=3.3.1=h4ab18f5_0
  - orc=1.9.2=h7829240_1
  - pandoc=3.1.11.1=ha770c72_0
  - pango=1.50.14=ha41ecd1_2
  - pcre2=10.42=hcad00b1_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-xgboost=2.0.3=cpu_pyh995e691_4
  - python=3.7.12=hf930737_100_cpython
  - pyyaml=6.0=py37h5eee18b_1
  - quarto=1.4.550=ha770c72_1
  - r-abind=1.4_5=r43hc72bb7e_1005
  - r-arrow=13.0.0=r43h59595ed_0
  - r-askpass=1.2.0=r43h57805ef_0
  - r-assertthat=0.2.1=r43hc72bb7e_4
  - r-babelgene=22.9=r43hc72bb7e_2
  - r-backports=1.4.1=r43h57805ef_2
  - r-base=4.3.2=hb8ee39d_2
  - r-base64enc=0.1_3=r43h57805ef_1006
  - r-beeswarm=0.4.0=r43h76d94ec_0
  - r-bh=1.84.0_0=r43hc72bb7e_0
  - r-bit=4.0.5=r43h57805ef_1
  - r-bit64=4.0.5=r43h57805ef_2
  - r-bitops=1.0_7=r43h57805ef_2
  - r-blob=1.2.4=r43hc72bb7e_1
  - r-boot=1.3_28.1=r43hc72bb7e_1
  - r-brew=1.0_10=r43hc72bb7e_0
  - r-brio=1.1.4=r43h57805ef_0
  - r-broom=1.0.5=r43hc72bb7e_1
  - r-bslib=0.6.1=r43hc72bb7e_0
  - r-cachem=1.0.8=r43h57805ef_1
  - r-cairo=1.6_1=r43hec52ca5_0
  - r-callr=3.7.3=r43hc72bb7e_1
  - r-car=3.1_2=r43h6115d3f_0
  - r-cardata=3.0_5=r43hc72bb7e_2
  - r-caret=6.0_94=r43h57805ef_1
  - r-catools=1.18.2=r43ha503ecb_2
  - r-circlize=0.4.15=r43hc72bb7e_2
  - r-class=7.3_22=r43h57805ef_1
  - r-cli=3.6.2=r43ha503ecb_0
  - r-clipr=0.8.0=r43hc72bb7e_2
  - r-clock=0.7.0=r43ha503ecb_1
  - r-clue=0.3_65=r43h57805ef_0
  - r-cluster=2.1.6=r43h61816a4_0
  - r-codetools=0.2_19=r43hc72bb7e_1
  - r-colorspace=2.1_0=r43h57805ef_1
  - r-commonmark=1.9.1=r43h57805ef_0
  - r-conquer=1.3.3=r43h08d816e_2
  - r-corrplot=0.92=r43hc72bb7e_2
  - r-cowplot=1.1.3=r43hc72bb7e_0
  - r-cpp11=0.4.7=r43hc72bb7e_0
  - r-crayon=1.5.2=r43hc72bb7e_2
  - r-credentials=2.0.1=r43hc72bb7e_0
  - r-crosstalk=1.2.1=r43hc72bb7e_0
  - r-curl=5.1.0=r43hf9611b0_0
  - r-data.table=1.14.10=r43h029312a_1
  - r-dbi=1.2.1=r43hc72bb7e_0
  - r-deldir=2.0_2=r43h61816a4_0
  - r-desc=1.4.3=r43hc72bb7e_0
  - r-devtools=2.4.5=r43hc72bb7e_2
  - r-diagram=1.6.5=r43ha770c72_2
  - r-diffobj=0.3.5=r43h57805ef_2
  - r-digest=0.6.34=r43ha503ecb_0
  - r-doparallel=1.0.17=r43hc72bb7e_2
  - r-dotcall64=1.1_1=r43h61816a4_0
  - r-downlit=0.4.3=r43hc72bb7e_0
  - r-dplyr=1.1.4=r43ha503ecb_0
  - r-dqrng=0.3.2=r43ha503ecb_0
  - r-dt=0.33=r43hc72bb7e_1
  - r-e1071=1.7_14=r43ha503ecb_0
  - r-ellipsis=0.3.2=r43h57805ef_2
  - r-evaluate=0.23=r43hc72bb7e_0
  - r-fansi=1.0.6=r43h57805ef_0
  - r-farver=2.1.1=r43ha503ecb_2
  - r-fastdummies=1.7.3=r43hc72bb7e_0
  - r-fastmap=1.1.1=r43ha503ecb_1
  - r-fastmatch=1.1_4=r43h57805ef_0
  - r-filelock=1.0.2=r43h76d94ec_0
  - r-fitdistrplus=1.1_11=r43hc72bb7e_1
  - r-fnn=1.1.4=r43ha503ecb_0
  - r-fontawesome=0.5.2=r43hc72bb7e_0
  - r-foreach=1.5.2=r43hc72bb7e_2
  - r-formatr=1.14=r43hc72bb7e_1
  - r-fs=1.6.3=r43ha503ecb_0
  - r-futile.logger=1.4.3=r43hc72bb7e_1005
  - r-futile.options=1.0.1=r43hc72bb7e_1004
  - r-future=1.33.1=r43hc72bb7e_0
  - r-future.apply=1.11.1=r43hc72bb7e_0
  - r-generics=0.1.3=r43hc72bb7e_2
  - r-gert=2.0.1=r43hc25a090_0
  - r-getopt=1.20.4=r43ha770c72_1
  - r-getoptlong=1.0.5=r43hc72bb7e_2
  - r-ggbeeswarm=0.7.2=r43h6115d3f_0
  - r-ggplot2=3.4.4=r43hc72bb7e_0
  - r-ggpubr=0.6.0=r43hc72bb7e_1
  - r-ggrastr=1.0.2=r43h6115d3f_0
  - r-ggrepel=0.9.5=r43ha503ecb_0
  - r-ggridges=0.5.6=r43hc72bb7e_0
  - r-ggsci=3.0.0=r43hc72bb7e_1
  - r-ggsignif=0.6.4=r43hc72bb7e_1
  - r-gh=1.4.0=r43hc72bb7e_1
  - r-gitcreds=0.1.2=r43hc72bb7e_2
  - r-globaloptions=0.1.2=r43ha770c72_2
  - r-globals=0.16.2=r43hc72bb7e_1
  - r-glue=1.7.0=r43h57805ef_0
  - r-goftest=1.2_3=r43h57805ef_2
  - r-gower=1.0.1=r43h57805ef_1
  - r-gplots=3.1.3.1=r43hc72bb7e_0
  - r-gprofiler2=0.2.3=r43hc72bb7e_1
  - r-gridextra=2.3=r43hc72bb7e_1005
  - r-gtable=0.3.4=r43hc72bb7e_0
  - r-gtools=3.9.5=r43h57805ef_0
  - r-hardhat=1.3.1=r43hc72bb7e_0
  - r-here=1.0.1=r43hc72bb7e_2
  - r-hexbin=1.28.3=r43h61816a4_1
  - r-highr=0.10=r43hc72bb7e_1
  - r-htmltools=0.5.7=r43ha503ecb_0
  - r-htmlwidgets=1.6.4=r43hc72bb7e_1
  - r-httpuv=1.6.14=r43ha503ecb_0
  - r-httr=1.4.7=r43hc72bb7e_0
  - r-httr2=1.0.0=r43hc72bb7e_0
  - r-ica=1.0_3=r43hc72bb7e_2
  - r-igraph=2.0.2=r43hbec7d4a_0
  - r-ini=0.3.1=r43hc72bb7e_1005
  - r-ipred=0.9_14=r43h57805ef_1
  - r-irlba=2.3.5.1=r43h316c678_1
  - r-isoband=0.2.7=r43ha503ecb_2
  - r-iterators=1.0.14=r43hc72bb7e_2
  - r-jquerylib=0.1.4=r43hc72bb7e_2
  - r-jsonlite=1.8.8=r43h57805ef_0
  - r-kableextra=1.4.0=r43hc72bb7e_1
  - r-kernlab=0.9_32=r43h08d816e_1
  - r-kernsmooth=2.23_22=r43h13b3f57_0
  - r-knitr=1.45=r43hc72bb7e_0
  - r-labeling=0.4.3=r43hc72bb7e_0
  - r-lambda.r=1.2.4=r43hc72bb7e_3
  - r-later=1.3.2=r43ha503ecb_0
  - r-lattice=0.22_5=r43h57805ef_0
  - r-lava=1.7.3=r43hc72bb7e_0
  - r-lazyeval=0.2.2=r43h57805ef_4
  - r-leiden=0.4.3.1=r43hc72bb7e_0
  - r-lifecycle=1.0.4=r43hc72bb7e_0
  - r-listenv=0.9.1=r43hc72bb7e_0
  - r-lme4=1.1_35.1=r43ha503ecb_0
  - r-lmtest=0.9_40=r43h61816a4_2
  - r-locfit=1.5_9.8=r43h57805ef_1
  - r-lsei=1.3_0=r43hd8f1df9_3
  - r-lubridate=1.9.3=r43h57805ef_0
  - r-magrittr=2.0.3=r43h57805ef_2
  - r-mass=7.3_60=r43h76d94ec_0
  - r-matrix=1.6_5=r43h316c678_0
  - r-matrixmodels=0.5_3=r43hc72bb7e_0
  - r-matrixstats=1.2.0=r43h57805ef_0
  - r-memoise=2.0.1=r43hc72bb7e_2
  - r-mgcv=1.9_1=r43h316c678_0
  - r-mime=0.12=r43h57805ef_2
  - r-miniui=0.1.1.1=r43hc72bb7e_1004
  - r-minqa=1.2.6=r43hcf54a89_0
  - r-mixtools=2.0.0=r43h57805ef_2
  - r-modelmetrics=1.2.2.2=r43ha503ecb_3
  - r-msigdbr=7.5.1=r43hc72bb7e_2
  - r-munsell=0.5.0=r43hc72bb7e_1006
  - r-nlme=3.1_164=r43h61816a4_0
  - r-nloptr=2.0.3=r43hb5eb8f6_0
  - r-nnet=7.3_19=r43h57805ef_1
  - r-npsurv=0.5_0=r43hc72bb7e_2
  - r-numderiv=2016.8_1.1=r43hc72bb7e_5
  - r-openssl=2.1.1=r43hb353fa6_0
  - r-packrat=0.9.2=r43hc72bb7e_0
  - r-parallelly=1.36.0=r43hc72bb7e_1
  - r-patchwork=1.2.0=r43hc72bb7e_0
  - r-pbapply=1.7_2=r43hc72bb7e_0
  - r-pbkrtest=0.5.2=r43hc72bb7e_1
  - r-pheatmap=1.0.12=r43h142f84f_0
  - r-pillar=1.9.0=r43hc72bb7e_1
  - r-pkgbuild=1.4.2=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_3
  - r-pkgdown=2.0.7=r43hc72bb7e_1
  - r-pkgload=1.3.4=r43hc72bb7e_0
  - r-plogr=0.2.0=r43hc72bb7e_1005
  - r-plotly=4.10.4=r43hc72bb7e_0
  - r-plyr=1.8.9=r43ha503ecb_0
  - r-png=0.1_8=r43h81d01c5_1
  - r-polyclip=1.10_6=r43ha503ecb_0
  - r-polynom=1.4_1=r43hc72bb7e_2
  - r-praise=1.0.0=r43hc72bb7e_1007
  - r-prettyunits=1.2.0=r43hc72bb7e_0
  - r-proc=1.18.5=r43ha503ecb_0
  - r-processx=3.8.3=r43h57805ef_0
  - r-prodlim=2023.08.28=r43ha503ecb_0
  - r-profvis=0.3.8=r43h57805ef_3
  - r-progressr=0.14.0=r43hc72bb7e_0
  - r-promises=1.2.1=r43ha503ecb_0
  - r-proxy=0.4_27=r43h57805ef_2
  - r-ps=1.7.6=r43h57805ef_0
  - r-purrr=1.0.2=r43h57805ef_0
  - r-quantreg=5.97=r43hd9ac46e_0
  - r-quarto=1.3=r43hc72bb7e_0
  - r-r.methodss3=1.8.2=r43hc72bb7e_2
  - r-r.oo=1.26.0=r43hc72bb7e_0
  - r-r.utils=2.12.3=r43hc72bb7e_0
  - r-r6=2.5.1=r43hc72bb7e_2
  - r-ragg=1.2.7=r43h73ae6e3_0
  - r-rann=2.6.1=r43ha503ecb_4
  - r-rappdirs=0.3.3=r43h57805ef_2
  - r-rcmdcheck=1.4.0=r43h785f33e_2
  - r-rcolorbrewer=1.1_3=r43h785f33e_2
  - r-rcpp=1.0.12=r43h7df8631_0
  - r-rcppannoy=0.0.22=r43ha503ecb_0
  - r-rcpparmadillo=0.12.8.0.0=r43h08d816e_0
  - r-rcppeigen=0.3.3.9.4=r43h08d816e_0
  - r-rcpphnsw=0.6.0=r43ha503ecb_0
  - r-rcppml=0.3.7=r43h884c59f_0
  - r-rcppprogress=0.4.2=r43hc72bb7e_3
  - r-rcpptoml=0.2.2=r43ha503ecb_1
  - r-rcurl=1.98_1.14=r43hf9611b0_0
  - r-readxl 
  - r-recipes=1.0.9=r43hc72bb7e_0
  - r-rematch2=2.1.2=r43hc72bb7e_3
  - r-remotes=2.4.2.1=r43hc72bb7e_0
  - r-renv=1.0.4=r43hc72bb7e_0
  - r-reshape2=1.4.4=r43ha503ecb_3
  - r-reticulate=1.35.0=r43ha503ecb_0
  - r-rjson=0.2.21=r43ha503ecb_3
  - r-rlang=1.1.3=r43ha503ecb_0
  - r-rmarkdown=2.25=r43hc72bb7e_0
  - r-rocr=1.0_11=r43hc72bb7e_3
  - r-roxygen2=7.3.1=r43ha503ecb_0
  - r-rpart=4.1.23=r43h57805ef_0
  - r-rprojroot=2.0.4=r43hc72bb7e_0
  - r-rsconnect=1.2.1=r43hc72bb7e_0
  - r-rspectra=0.16_1=r43h08d816e_2
  - r-rsqlite=2.3.4=r43ha503ecb_0
  - r-rstatix=0.7.2=r43hc72bb7e_1
  - r-rstudioapi=0.15.0=r43hc72bb7e_0
  - r-rsvd=1.0.5=r43hc72bb7e_2
  - r-rtsne=0.17=r43h7ce84a7_0
  - r-rversions=2.1.2=r43hc72bb7e_2
  - r-sass=0.4.8=r43ha503ecb_0
  - r-scales=1.3.0=r43hc72bb7e_0
  - r-scattermore=1.2=r43ha503ecb_1
  - r-sctransform=0.4.1=r43h08d816e_0
  - r-segmented=2.0_2=r43hc72bb7e_0
  - r-sessioninfo=1.2.2=r43hc72bb7e_2
  - r-seurat=5.0.1=r43ha503ecb_0
  - r-seuratobject=5.0.1=r43ha503ecb_0
  - r-shape=1.4.6=r43ha770c72_2
  - r-shiny=1.8.0=r43h785f33e_0
  - r-sitmo=2.0.2=r43ha503ecb_2
  - r-snow=0.4_4=r43hc72bb7e_2
  - r-sourcetools=0.1.7_1=r43ha503ecb_1
  - r-sp=2.1_3=r43h57805ef_0
  - r-spam=2.10_0=r43h9f9f741_0
  - r-sparsem=1.81=r43h61816a4_2
  - r-spatstat.data=3.0_4=r43hc72bb7e_0
  - r-spatstat.explore=3.2_6=r43h57805ef_0
  - r-spatstat.geom=3.2_8=r43h57805ef_0
  - r-spatstat.random=3.2_2=r43ha503ecb_0
  - r-spatstat.sparse=3.0_3=r43h57805ef_0
  - r-spatstat.utils=3.0_4=r43h57805ef_0
  - r-squarem=2021.1=r43hc72bb7e_2
  - r-statmod=1.5.0=r43hd8f1df9_1
  - r-stringi=1.8.3=r43h9facbd6_0
  - r-stringr=1.5.1=r43h785f33e_0
  - r-survival=3.5_7=r43h57805ef_0
  - r-sys=3.4.2=r43h57805ef_1
  - r-systemfonts=1.0.5=r43haf97adc_0
  - r-tensor=1.5=r43hc72bb7e_1005
  - r-testthat=3.2.1=r43ha503ecb_0
  - r-textshaping=0.3.7=r43hd87b9d6_0
  - r-tibble=3.2.1=r43h57805ef_2
  - r-tidyr=1.3.1=r43ha503ecb_0
  - r-tidyselect=1.2.0=r43hc72bb7e_1
  - r-timechange=0.3.0=r43ha503ecb_0
  - r-timedate=4032.109=r43hc72bb7e_0
  - r-tinytex=0.49=r43hc72bb7e_1
  - r-tzdb=0.4.0=r43ha503ecb_1
  - r-urlchecker=1.0.1=r43hc72bb7e_2
  - r-usethis=2.2.2=r43hc72bb7e_0
  - r-utf8=1.2.4=r43h57805ef_0
  - r-uwot=0.1.16=r43ha503ecb_0
  - r-vctrs=0.6.5=r43ha503ecb_0
  - r-vipor=0.4.5=r43h142f84f_0
  - r-viridis=0.6.4=r43h6115d3f_0
  - r-viridislite=0.4.2=r43hc72bb7e_1
  - r-visnetwork=2.1.2=r43hc72bb7e_3
  - r-waldo=0.5.2=r43hc72bb7e_0
  - r-whisker=0.4.1=r43hc72bb7e_1
  - r-withr=3.0.0=r43hc72bb7e_0
  - r-xfun=0.42=r43ha503ecb_0
  - r-xgboost=2.0.3=cpu_r43h5cb4a28_4
  - r-xml=3.99_0.16.1=r43hc6530ce_0
  - r-xml2=1.3.6=r43hbfba7a4_1
  - r-xopen=1.0.0=r43hc72bb7e_1005
  - r-xtable=1.8_4=r43hc72bb7e_5
  - r-yaml=2.3.8=r43h57805ef_0
  - r-zip=2.3.1=r43h57805ef_0
  - r-zoo=1.8_12=r43h57805ef_1
  - rdma-core=51.0=hd3aeb46_0
  - re2=2023.06.02=h2873b5e_0
  - readline=8.2=h8228510_1
  - s2n=1.4.3=h06160fa_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37hf838250_2
  - sed=4.8=he412f7d_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - sqlite=3.45.1=h2c6b66d_0
  - sysroot_linux-64=2.12=he073ed8_16
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - toml=0.10.2=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - ucx=1.15.0=h75e419f_3
  - wheel=0.42.0=pyhd8ed1ab_0
  - xgboost=2.0.3=cpu_pyhb8f9a19_4
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yq=3.2.3=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
